### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by terunobu3** [terunobu3/furima-40515#20]
#URL
https://furima-40515.onrender.com/

**Comment by shodai-ito** [comment]
@terunobu3 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **購入機能**
- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
カード情報が入力できず、購入が不可となっております。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by terunobu3** [comment]
レビューありがとうございます。
renderで本番環境の公開キー秘密キーの設定をし忘れていました。
再チェックお願いします。

**Comment by terunobu3** [comment]
画像がうまく表示されないのは config/enviroments/production.rbの
config.active_strage.service = :local　が原因でしょうか？
ここはawsなどを利用するのでしょうか？　参考サイトはどこでしたっけ？

**Comment by shodai-ito** [comment]
@terunobu3 さん、修正作業ありがとうございます！

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます！
最終課題「FURIMA」の開発、お疲れ様でした。

いただいた質問にも回答させていただきます。
表示されない原因としてはおっしゃる通りです！
カリキュラムでは「AWSに画像をアップロードする」の項目に詳細が記載されております！

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
